services:
  api:
    build:
      target: builder
    command: pnpm --filter @app/api dev
    environment:
      WHO_DATABASE_PATH: /repo/data/who.db
      DATABASE_URL: /repo/data/data.db
    volumes:
      - ./apps/api/src:/repo/apps/api/src
      - ./packages/shared/src:/repo/packages/shared/src
      - ./packages/database/src:/repo/packages/database/src
      - ./data:/repo/data

  web:
    build:
      target: builder
    command: pnpm --filter @app/web dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./apps/web/app:/repo/apps/web/app
      - ./apps/web/components:/repo/apps/web/components
      - ./apps/web/lib:/repo/apps/web/lib
      - ./packages/shared/src:/repo/packages/shared/src
